### ISSUE TITLE
Add generics to GridFieldConfig

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripeltd/silverstripe-framework-generics#4]
## PRs
- https://github.com/silverstripeltd/silverstripe-framework-generics/pull/18

**Comment by Cambis** [comment]
This should come after #9

**Comment by GuySartorelli** [comment]
Looks like this didn't need the arraylist thing done first (I got mixed up and did this instead of what I had assigned myself for, but that worked out in the end)
