### ISSUE TITLE
 Add generics to `ArrayList`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripeltd/silverstripe-framework-generics#9]
Found this tricky initially but now that I have a better understanding of how it works I'll give it another go.

## PRs
- https://github.com/silverstripeltd/silverstripe-framework-generics/pull/14
- https://github.com/silverstripeltd/silverstripe-framework-generics/pull/15
- https://github.com/silverstripeltd/silverstripe-framework-generics/pull/17

**Comment by Cambis** [comment]
I'm thinking that there might be some hidden logic in ArrayList that is making my IDE confused, this is how it resolves for me

```
/** @var ArrayList<string[]> */
$foo = ArrayList::create();
foreach ($foo as $item) {
    /** @var T $item */
}

/** @var DataList<File> */
$bar = DataList::create();

foreach ($bar as $item) {
    /** @var DataObject|File|null $item */
}
```

Go with #15 for now, have a look at the tests here https://github.com/ramsey/collection/blob/main/tests/types/collections.php, these should work for us nicely

**Comment by Cambis** [comment]
ooh and you might need to set
```
 /**
  * @return Tranversable<array-key, T>
  */
 public function getIterator(): Traversable
```

**Comment by GuySartorelli** [comment]
Sweet, thanks.
I'll leave tests out for now - that might be a good focus for tomorrow possibly.

**Comment by GuySartorelli** [comment]
15 merged
